### ISSUE TITLE
Add tiles to Hubitat Dashboard

### ISSUE THREAD

**Issue by drfant** [DaveGut/HubitatActive#10]
Hello Dave,   is there a way to add a tile for the kasa lamps to the dashboard.  I could not find a way to do that.

**Comment by DaveGut** [comment]
After adding the device to the dashboard (like any other), it can be added as a bulb or color bulb, depending on the device.

**Comment by drfant** [comment]
Dave.  The problem is that the new lamps do not show up in my pick a device list.   Thoughts??

Sent from my iPhone. Typos are authorized. 

Dale

**Comment by DaveGut** [comment]
Make sure the devices are added to the individual dashboard first.
