### ISSUE TITLE
Metadata Error:Please check if you inadvertently pasted driver code into apps code window on line 29

### ISSUE THREAD

**Issue by MPDano** [DaveGut/HubitatActive#11]
tried importing and got this line error.  Any suggestions?

**Comment by DaveGut** [comment]
Definitely insufficient information.  What driver were you trying to paste into what environment?  Generally, to paste a driver, you open the driver in gitHub, select "raw" in upper right of browser, then copy.  That avoids errors.

**Comment by MPDano** [comment]
Thanks for that.  Import gave the error in the error title.  Doing a raw copy/paste yielded no errors.  Thanks for the tip

**Comment by DaveGut** [comment]
Resolved.
