### ISSUE TITLE
Create the Device after importing drivers

### ISSUE THREAD

**Issue by MPDano** [DaveGut/HubitatActive#12]
Sorry for all these questions but I can seem to find where I "create the device" option is.  I see the Samsung TV Remote after importing the driver but no where do I see to create a device.  In Hubitat there is a devices link but that just shows what currently exists.  Searching within the raw code show no place to enter an ip "samsung tv ip."

**Comment by DaveGut** [comment]
download the file Samsung TV Remote.pdf to your desktop.  It has instructions on how to install.  GitHub is not the forum for how to install into Hubitat.  You are better served using Hubitat (more people to help).  

Hubitat:  https://community.hubitat.com/

You will need to join.  Free.

Thread:  https://community.hubitat.com/t/samsung-hubitat-tv-integration-2016-and-later/55120

Dave
