### ISSUE TITLE
KasaDevices does not support larger than /24 subnets

### ISSUE THREAD

**Issue by sfabel** [DaveGut/HubitatActive#15]
In my home, I have assigned 10.0.0.0/8 to my IoT network and the DHCP address range spans across all of these addresses. The way KasaDevices is constructing the hosts to scan when adding devices is such that it is impossible to enter values into the "Lan Segments" and "Host Address Range" fields that would properly construct a class A network address to scan for in the findDevices() function.

I am not familiar enough with Groovy to go ahead and just adjust this myself, but it seems to me that allowing to scan a network based on the network and a mask would solve this problem?

**Comment by DaveGut** [comment]
I support Class C networks only.  Time to scan a class A network could be impossibly excessive.  Assuming the final format for the address is AAA.BBB.CCC.DDD, you could install a device at a time using segment = AAA.BBB.CCC and host range = DDD, DDD.  Will look for one device.

UPDATE:  Another method is to use the Kasa Cloud to discover the devices.  That returns the IP address to the app and when installed, sets the IP address.

**Comment by sfabel** [comment]
Thanks. It times out for me when trying to discover using CLOUD.

`2021-11-03 03:08:38.569 pm errorjava.net.SocketTimeoutException: Read timed out on line 862 (method addDevicesPage)`

**Comment by DaveGut** [comment]
Tested on my Hubitat Hub and did not have an issue.  Only thing I can think to try is updating your token then trying again.  I think this will be of no use.  The uri I use is the same as all other Kasa integrations on gitHub for getting devices.  The code itself is straight-forward and has been in-use for several years without issue.

You are welcome to look and give me your thoughts where I can fix the issue.  The hubitat documentation on the httpPostJson comms is located at: https://docs.hubitat.com/index.php?title=Common_Methods_Object#httpPostJson

Dave

**Comment by DaveGut** [comment]
Can not duplicate.  This is code that has been in effect for 4 years.

- Try the following (all in the my app):
  - Edit the app, adding at line 861 a new line 
    - "log.trace commandParams"
  - Update the kasa Token
  - Add Devices

Provide me with the log for the app only.

**Comment by DaveGut** [comment]
Closed.  No further activity and I can not do the code to repair.
