### ISSUE TITLE
Package Manager Update Fails

### ISSUE THREAD

**Issue by capritzl** [DaveGut/HubitatActive#17]
Kasa Local Hubitat Integration, version 6.4.3-rel1 

I receive the following errors when I try to perform an upgrade via Package Manager.

app:172021-12-09 04:41:33.555 pm infoFatal error occurred, rolling back
app:172021-12-09 04:41:33.549 pm errorError upgrading app: groovyx.net.http.HttpResponseException: status code: 500, reason phrase: Server Error
app:172021-12-09 04:41:33.347 pm infoUpgrading Kasa Integration
app:172021-12-09 04:41:33.345 pm errorError retrieving app source: groovyx.net.http.HttpResponseException: status code: 500, reason phrase: Server Error
app:172021-12-09 04:41:32.704 pm infoDownloading Kasa Integration error

Automatic update failure: [success:false, succeeded:[], failed:[https://raw.githubusercontent.com/DaveGut/HubitatActive/master/KasaDevices/packageManifest.json], message:An error occurred while installing the package: Failed to upgrade app https://raw.githubusercontent.com/DaveGut/HubitatActive/master/KasaDevices/Application/KasaIntegrationApp.groovy.]

**Comment by DaveGut** [comment]
Could not duplicate.  Problem is with either HPM or some problem with GitHub.  I tried a fresh install - so the package definitions (manifest) is correct.
