### ISSUE TITLE
Kasa KL430 implementation

### ISSUE THREAD

**Issue by jbbarnes77** [DaveGut/HubitatActive#2]
I have 75 Kasa devices on my network, representing over a dozen products. The drivers are working fine.

The only unsupported device is the KL430 RGB LED strip. I can offer to test drivers on mine if you do not have one to test with.

Brandon

**Comment by DaveGut** [comment]
You can do a manual installation by creating a virtual device using the Color Bulb driver.  Turn on Debug logging and do a refresh - providing me with logging.  Then, for the driver, what functions work / do not work.  And for the Kasa App, are there critical functions missing.

**Comment by DaveGut** [comment]
App updated to accept KL430 as a color bulb.

**Comment by jbbarnes77** [comment]
I noted the update to the application. I used the new code to update the Kasa Integration app. Didn't see any changes to the drivers, so that was the only new code I installed.

Upon rerunning the Integration app, it listed my KL430 and allowed me to add it. So it does show as a current device now. It will not, however, respond. I can't turn it on or off or make any brightness or color changes. 

I can provide assistance in documenting and troubleshooting.

**Comment by jbbarnes77** [comment]
Dave,

Thanks for the new code. I tested it and added a comment to the case, 
but it remained closed. So I'm not sure if my comment gets highlighted 
or not.

In case it doesn't, here's what I added:

I noted the update to the application. I used the new code to update the 
Kasa Integration app. Didn't see any changes to the drivers, so that was 
the only new code I installed.

Upon rerunning the Integration app, it listed my KL430 and allowed me to 
add it. So it does show as a current device now. It will not, however, 
respond. I can't turn it on or off or make any brightness or color changes.

I can provide assistance in documenting and troubleshooting.

Brandon

**Comment by DaveGut** [comment]
I need some data for the strip.  Enable debug logging and run a single Refresh.  I need to see the data from the refresh.
(we are not alone, others are having problems also).
Dave

**Comment by DaveGut** [comment]
Brandon,
I have developed a test driver.  Location is:  []https://raw.githubusercontent.com/DaveGut/Hubitat-TP-Link-Integration-DEPRECATED/master/LightstripTest.groovy


Instructions:

- Install code as new driver
- Open a Log Page
- Add a new device manually
- In preferences, enter the IP address of the strip.
- Commands // Observations

1. - Refresh // debug entry in log
2. - On // light turns on (if fails, stop), attribute switch = on
3. - Off // light turns off, attribute switch = off
4. - Set Level 50 // light on to a level of 50, attribute level = 50
5. - Set Circadian //  Light changes color temperature // attribute color temp changes
6. - Set Color Temperature 6500 // CT changes to 6500, attribute CT = 6500
7. - Set Color (pick any) // Color Changes, attribute CT = 0, color attributes change.

**Comment by DaveGut** [comment]
Code has been updated to include the KL430.  May or may not work.
