### ISSUE TITLE
Mono and Light Strip Links should be Raw versions

### ISSUE THREAD

**Issue by selner** [DaveGut/HubitatActive#21]
in https://github.com/DaveGut/HubitatActive/blob/master/KasaDevices/README.md, the last two links fail because they aren't using the raw variant as the ones directly above them do.

Should instead be linked to:

- https://raw.githubusercontent.com/DaveGut/HubitatActive/master/KasaDevices/DeviceDrivers/WhiteBulb.groovy

- https://raw.githubusercontent.com/DaveGut/HubitatActive/master/KasaDevices/DeviceDrivers/LightStrip.groovy

**Comment by DaveGut** [comment]
Fixed.  Thanks for the catch.
