### ISSUE TITLE
Error on Kasa Integration app

### ISSUE THREAD

**Issue by maxtacu** [DaveGut/HubitatActive#22]
after creating the Kasa Integration app with imported code, the app can not initialize and throws the error
```
java.lang.NullPointerException: Cannot get property 'version' on null object on line 1147 (method initInstance)
```

**Comment by DaveGut** [comment]
Could not duplicate on existing 6.6.0 app baseline.  Possible cause is an intermittent glitch in gitHub communications (it happens once in a while).  Suggest trying again and providing more log data before the above log line.

**Comment by DaveGut** [comment]
Closing due COULD NOT DUPLICATE and lack of further response from submitter.
