### ISSUE TITLE
Updated weeks ago but still says "update available"

### ISSUE THREAD

**Issue by Valorguy44** [DaveGut/HubitatActive#27]
Not sure if I need to really do anything - it's working perfectly, but the APPS page says "Update Available".

Using the Hubitat Package manager, it doesn't show a new version.  I'm on 6.7.1

Should I just not worry about it?

![image](https://user-images.githubusercontent.com/108855578/193365151-6c280539-a223-42ec-9eb0-f1dc7ff6cd77.png)

**Comment by DaveGut** [comment]
Simply press configure on any devices sdit page.  Will fix this.  But it has zero impact.

Dave Gutheinz
________________________________
From: Valorguy44 ***@***.***>
Sent: Friday, September 30, 2022 5:33:12 PM
To: DaveGut/HubitatActive ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DaveGut/HubitatActive] Updated weeks ago but still says "update available" (Issue #27)


Not sure if I need to really do anything - it's working perfectly, but the APPS page says "Update Available".

Using the Hubitat Package manager, it doesn;t show a new version.

Should I just not worry about it?
