### ISSUE TITLE
Support for the ES20M (Motion Dimmer Switch) 

### ISSUE THREAD

**Issue by the-garz** [DaveGut/HubitatActive#28]
Any support or plan to add this new motion actived dimmer switch? Kasa ES20M. 🤞

https://www.kasasmart.com/us/products/smart-switches/smart-wifi-dimmer-switch-es20m

**Comment by DaveGut** [comment]
Hopefully.  In the meantime, the dimming switch should control the dimming functions.

Issue:  Basic control of PD functions should be relative easy (a lot of them); however, I am looking for a means to report motion from the device to Hubitat.  Still do not see it; however, it could be as using the built-in motion detect function to turn light on and then Hubitat catch the on event for follow-on activities.

Dave

**Comment by DaveGut** [comment]
The ES20M is supported in Hubitat as a dimming switch.  It does not report motion.  The motion detect from these plugs is not exposed in any known Kasa interface.

Dave
