### ISSUE TITLE
KasaDevices: Password with special characters fails authentication

### ISSUE THREAD

**Issue by TonyFleisher** [DaveGut/HubitatActive#29]

**Comment by TonyFleisher** [comment]
When entering a password that contains the less-than character "<", the hubitat client libraries escapes the html entity and stores it as "&amp;lt;"

For example, if you enter a password as: "123<>abc"

Request URL: http://HUB_IP/installedapp/update/json
Request Method: POST

Payload sent by Browser to the Hub:
`settings[userPassword]: 
123&lt;>123`

As a result, the settings is stored with the html entity which then needs to be unescaped when sending to the cloud to login.

**Comment by DaveGut** [comment]
Fixed on version 6.7.2 update.
