### ISSUE TITLE
No issue here, just want to say Thanks!

### ISSUE THREAD

**Issue by uncdubdiver** [DaveGut/HubitatActive#33]
Thanks for keeping this integration up-to-date. I swear every single time there's a Hubitat release (which is about once-twice a week), it breaks the Kasa integration. Thanks for keeping things in line and working like they are supposed to!

**Comment by DaveGut** [comment]
You are welcome.  There are some hiccups in going from a Community to a Built-In integration.  The Hubitat staff has been very responsive to some critical changes to support a wider user-base.  And I am by no means perfect.
