### ISSUE TITLE
Samsung multiroom app driver 4.0 issue

### ISSUE THREAD

**Issue by nrm94ee330** [DaveGut/HubitatActive#36]
since updating last week to the 4.0 version from 3.3.8, my Samsung R1 speaker stopped working..
I received many errors, including 

Speaker 4.0 groupStop: Not a Grouped speaker.
Speaker 4.0 addToQueue: [status:aborted, reason:Speaker not on LAN]

So I uninstalled and reinstalled the app and ran the app in hubitat

and I had some success ... 

Speaker 4.0 sendSyncCmd: [cmd:/UIC?cmd=%3Cname%3EGetFunc%3C/name%3E, host:http://192.168.1.3:55001, method:CurrentFunc, data:wifidlna]
Speaker 4.0 extractData: method = CurrentFunc, data = wifidlna
Speaker 4.0 refreshParse: [isConnected:yes]

but then anytime a "speak" command is given...
I get  Speaker 4.0 addToQueue: [status:aborted, reason:Speaker not on LAN]

So I manually copied the v 3.3.8 of driver..
and everything started to work immediately.

I have another hubitat hub that I use for dev purposes..
which is completely clean..
so I installed the whole thing from HPM..
 and enabled debug logs..
ran the app and found my speaker and added it..
but if I click speak .. etc it doesnt play/speak.

here are all the logs from the clean install

dev:11 2022-12-05 08:46:55.828 AMdebugSpeaker 4.0 playTextAndResume: [status:addToQueue, text:test, volume:null]
dev:11 2022-12-05 08:46:55.827 AMdebugSpeaker 4.0 addToQueue: [status:aborted, reason:Speaker not on LAN]
dev:11 2022-12-05 08:46:55.826 AMwarnSpeaker 4.0 addToQueue: [status:aborted, reason:Speaker not on LAN]
dev:11 2022-12-05 08:46:46.382 AMdebugSpeaker 4.0 setTrackDescription: [subMode:dlna, trackData:{"trackLength":0,"artist":"unknown","album":"unknown","title":"unknown","type":"unknown"}]
dev:11 2022-12-05 08:46:46.380 AMdebugSpeaker 4.0 scheduleSetTrackDescription: [updateTrackDescription:true, status:notScheduled, reason:null or 0 timelength]
dev:11 2022-12-05 08:46:46.377 AMdebugSpeaker 4.0 sendSyncCmd: [cmd:/UIC?cmd=%3Cname%3EGetCurrentPlayTime%3C/name%3E, host:http://192.168.12.3:55001, method:MusicPlayTime, data:00]
dev:11 2022-12-05 08:46:46.375 AMdebugSpeaker 4.0 extractData: method = MusicPlayTime, data = 00
dev:11 2022-12-05 08:46:46.249 AMdebugSpeaker 4.0 sendSyncCmd: [cmd:/UIC?cmd=%3Cname%3EGetMusicInfo%3C/name%3E, host:http://192.168.12.3:55001, method:MusicInfo, data:Playing Status is not valid or MusicDB is NULL]
dev:11 2022-12-05 08:46:46.246 AMdebugSpeaker 4.0 extractData: method = MusicInfo, data = Playing Status is not valid or MusicDB is NULL
dev:11 2022-12-05 08:46:46.133 AMdebugSpeaker 4.0 sendSyncCmd: [cmd:/UIC?cmd=%3Cname%3EGetFunc%3C/name%3E, host:http://192.168.12.3:55001, method:CurrentFunc, data:wifidlna]
dev:11 2022-12-05 08:46:46.127 AMdebugSpeaker 4.0 extractData: method = CurrentFunc, data = wifidlna
dev:11 2022-12-05 08:46:44.114 AMdebugSpeaker 4.0 extractData: method = AcmMode, data = aasync00:00:00:00:00:00none
dev:11 2022-12-05 08:46:44.092 AMdebugSpeaker 4.0 refreshParse: [isConnected:yes]
dev:11 2022-12-05 08:46:44.019 AMdebugSpeaker 4.0 extractData: method = CurrentFunc, data = wifidlna
dev:11 2022-12-05 08:46:44.000 AMdebugSpeaker 4.0 sendCmd: [command: /UIC?cmd=%3Cname%3EGetAcmMode%3C/name%3E, host: 192.168.12.3:55001]
dev:11 2022-12-05 08:46:43.989 AMdebugSpeaker 4.0 getPlayStatus: [source: wifi, submode: dlna]
dev:11 2022-12-05 08:46:43.987 AMdebugSpeaker 4.0 sendSyncCmd: [cmd:/UIC?cmd=%3Cname%3EGetPlayStatus%3C/name%3E, host:http://192.168.12.3:55001, method:CurrentFunc, data:wifidlna]
dev:11 2022-12-05 08:46:43.985 AMdebugSpeaker 4.0 extractData: method = CurrentFunc, data = wifidlna
dev:11 2022-12-05 08:46:43.976 AMdebugSpeaker 4.0 extractData: method = CurrentFunc, data = wifidlna
dev:11 2022-12-05 08:46:43.882 AMdebugSpeaker 4.0 sendCmd: [command: /UIC?cmd=%3Cname%3EGetVolume%3C/name%3E, host: 192.168.12.3:55001]
dev:11 2022-12-05 08:46:43.875 AMdebugSpeaker 4.0 sendCmd: [command: /UIC?cmd=%3Cname%3EGetFunc%3C/name%3E, host: 192.168.12.3:55001]
dev:11 2022-12-05 08:46:38.749 AMinfoupdated: [status:updating, infoLog:null, debugLog:true, refreshInt:refresh]
dev:11 2022-12-05 08:46:38.609 AMdebugSpeaker 4.0 clearQueue
dev:11 2022-12-05 08:46:38.308 AMwarnSpeaker 4.0 addToQueue: [status:aborted, reason:Speaker not on LAN]
dev:11 2022-12-05 08:46:14.044 AMinfoupdated: [status:updating, infoLog:null, debugLog:false, refreshInt:refresh]
dev:11 2022-12-05 08:46:13.980 AMinfoInstalling ..

**Comment by nrm94ee330** [comment]
Trying to troubleshoot..
I commented out the if block under //	========== Play Queue Execution ==========

  if (device.currentValue("isConnected") == "yes") {
and the else block.. as well

and now it seems to be working fine... 

I also added "device.currentValue" in debugs.. and everytime I get null in that...
and so the "isConnected" == yes block is never executed.

**Comment by DaveGut** [comment]
Did you do a save preferences? This will activate the new attribute ("isConnected") which is critical to preventing queue hanging.

**Comment by DaveGut** [comment]
Closed due to lack of response for further action.
