### ISSUE TITLE
Samsung Cooking Range/Oven Light

### ISSUE THREAD

**Issue by nrm94ee330** [DaveGut/HubitatActive#37]
Hello,
 Was wondering if a controllable switch for the "Oven Light" (called 'lamp') can be added to the "Samsung Oven" or "Cavity"
I looked through the "ST Data Collect" and added the code for getting the status of the lamp, but I am unsure how the code works.. so dont understand yet on how to add a lamp on/off switch..

**Comment by DaveGut** [comment]
Incorporated into the HubiThings Replica version of the product.  I am deprecating the existing version in the near future.
