### ISSUE TITLE
Unprocessable Entity

### ISSUE THREAD

**Issue by nrm94ee330** [DaveGut/HubitatActive#38]
Hello, 
When I set the oven setpoint and "Run Oven" I am getting 
Cooking Range: setMachineState: [comp: main, state: running, status: [status:FAILED, httpCode:Timeout, errorMsg:groovyx.net.http.HttpResponseException: status code: 422, reason phrase: Unprocessable Entity]]

I am getting all the current states correctly.. with the Smartthings device ID for the cooking range

**Comment by DaveGut** [comment]
Range product is being converted to the HubiThings Replica version.  The version you are talking about is deprecated.  HubiThings replica provides a far superior interface to SmartThings for device control than in the existing code.
