### ISSUE TITLE
Kasa HS100 switch - switch status doesn't update

### ISSUE THREAD

**Issue by snarkywolverine** [DaveGut/HubitatActive#39]
I'd like some help troubleshooting this.

I have an HS100 switch with a hard-coded IP.  I can control the switch in Hubitat using the On/Off buttons (The switch actually turns on/off as expected), but the 'switch' field in Current State stays 'off'. I also no longer see setSysinfo logs in the past logs, even though 'Enable Information Logging' has been enabled for the last week+.  (Events are logging properly, it seems).

I changed the polling interval from 1 min to 30 sec today (to avoid re-calling connect) - so far, that hasn't helped.

I also checked that the HS 100 has firmware 1.2.5 in the Kasa app (I wasn't prompted to update it, so I'm guessing that's latest).

Any ideas?

driverVersion: 6.6.0
feature: TIM
model: HS100

**Comment by DaveGut** [comment]
It is possibly a hub load problem.  Is the switch state being picked up by rules?  One test is to refresh the browser and see if the state updates.

**Comment by snarkywolverine** [comment]
The switch state is not immediately picked up by the rules or by a refresh in the browser.  Today, for instance, the switch state was updated (and the smart switch turned on) about an hour before the switch value was updated (and the corresponding rules were also updated).

I have ~20 devices (5-7 are virtual or scenes), 4 notifications, and maybe 20 rules (either basic or 5.1). I also have minimal google home integration.  I'm guessing disabling logging will help, but I wouldn't think this would cause much load -- do you agree with that assessment? If so, anything else I should try?

I should also add that, when the device 'switch' setting doesn't match, I tried to click "refresh" -- but that also didn't update the state (after refreshing the browser).

**Comment by DaveGut** [comment]
First, update to the latest driver version.  That way we are on the same version page.

Second, you need to look at the log when you send the command and compare to the EVENT log (device's edit page at top has button to access this log and see when the event was sent.

Third, if there is a significant lag reflected in the event log, I you to enable debug logging then capture a single device's log when the delay is occurring.  Only send the command.  Do not physically do a refresh.

What happens in the driver:

- From hubitat:  The command is sent and a response is received.  Once the response is received, a refresh is called to get the device state.
- Physical paddle activation.  The update is caught at the next automatic poll.

**Comment by DaveGut** [comment]
Closed due to lack of further response from originator.
