### ISSUE TITLE
KasaDevices rawSocketTimeout after updating to 6.0.0

### ISSUE THREAD

**Issue by jtp10181** [DaveGut/HubitatActive#4]
I cant seem to control my HS200 switch with LAN after updating to 6.0.0. It was working before using the lan app, and the device doesn't have any firmware updates. 

If I switch on the cloud control it seems to be working, just the LAN control is not working.

![image](https://user-images.githubusercontent.com/99599/105580605-00155980-5d53-11eb-92aa-eb1304dacf24.png)

**Comment by DaveGut** [comment]
Updated with comments on Hubitat thread.
Dave Gutheinz

**Comment by DaveGut** [comment]
Closed.  See Hubitat thread.
