### ISSUE TITLE
Replica Oven

### ISSUE THREAD

**Issue by almulder** [DaveGut/HubitatActive#41]
Replica Oven does not look like it take into account the Flex ovens, I have the divider that when removed it one oven, when added its upper and lower over independent of each other.

Also any Idea when you might bring the Flex Washer and Flex Dryer over to replica?

**Comment by DaveGut** [comment]
First, the flex (i.e., divider) is a part of the installation as a child.  Before installing the oven, you must install both the oven and oven child driver.  On install of the main, the child is installed.

That being said, an update is coming this next week.

Washer / Dryer:  Several weeks.
