### ISSUE TITLE
Samsung remote WS command

### ISSUE THREAD

**Issue by Sean-Nunan** [DaveGut/HubitatActive#42]
Hi Dave,
I am looking for a command to open the ws connection. Currently, when I send a command, for example, "power off", if the ws is closed, it connects the ws but seems to drop the command so I have to send again. 
The use case would be to connect the ws when the display is selected in my user interface and enable the control buttons when the ws is open.

Unless I totally missed it in the docs, it happens.

Thanks in advance.

**Comment by DaveGut** [comment]
Will not add that command.  In two years, no issue has been reported in the WS connection.  You may modify your copy of the code as you see fit.

**Comment by DaveGut** [comment]
Fixed in latest version

**Comment by Nunan4265** [comment]
Thank you!
