### ISSUE TITLE
Issue with EM Multi Plugs on IP control

### ISSUE THREAD

**Issue by yehudag** [DaveGut/HubitatActive#43]
Not able to turn on or off EM Multi Plug devices and showing this log error:
`Yehuda Monitor Left-2.3.5-1: parseUdp: [error: error, reason: not LAN_TYPE_UDPCLIENT, respType: LAN_TYPE_UDPCLIENT_ERROR]`

**Comment by DaveGut** [comment]
Tested but can not duplicate.  Need the following data:
a. Plug Model (i.e., KP115)
b. Data from the following

- Set Preference Reboot to true.
- Set Preference Enable debug logging to true.
- Open a log page.
- Run Save Preferences.

**Comment by yehudag** [comment]
Hmmm, seems reboot resolved and no more issues
