### ISSUE TITLE
Samsung TV Remote Buttons exported from Hubitat to HomeKit

### ISSUE THREAD

**Issue by ColinDarwin** [DaveGut/HubitatActive#44]
Hey is there any way to have the buttons in the HE Samsung TV Remote device exported to Apple HomeKit?  All I get is a switch that turns the TV on/off.

**Comment by DaveGut** [comment]
Not that I can implement.  It would be a function of the Hubitat -> Homekit implementation (both Hubitat ans Homekit sides of the integration).

**Comment by ColinDarwin** [comment]
Ok so the work needs to be implemented within the HomeKit integration App on Hubitat?  Yeah?

**Comment by DaveGut** [comment]
No, both the Homekit and Hubitat side may need updating.

**Comment by DaveGut** [comment]
No correction required.  Closing.
