### ISSUE TITLE
Led control not working

### ISSUE THREAD

**Issue by gmaus60** [DaveGut/HubitatActive#5]
In the old version, I could turn off the LED indicator for all Kasa devices.   I have HS200, HS210, S220 and HS103.   None are honoring the LED setting with this newest driver - 6.1.0.

**Comment by DaveGut** [comment]
Fixed in quickFix 6.1.0.1.  Reload driver using "import" and test again.

**If this works, please reply and close issue.**

**Comment by gmaus60** [comment]
That did the trick.   Thanks!
