### ISSUE TITLE
Realtime updates

### ISSUE THREAD

**Issue by gmaus60** [DaveGut/HubitatActive#6]
The old drivers used to update status in the dashboard nearly in real-time.   When I operate a physical Kasa switch, the status of the device is not shown in the Habitat dashboard.  There is a serious delay, unless I set polling on the device to 5 seconds.   Even this delay is less than desirable.    Is this behavior intended?    All of my Kasa devices used to provide very fast feedback except for a 3way switch model HS210.  I had assumed this was a limitation of the device or the firmware on that device.

**Comment by DaveGut** [comment]
My old drivers never did quick polling faster than every 5 seconds.  There are Hubitat performance issues in faster polling.  The delay will average approximately 1/2 of the poll/refresh interval (5, 10, 20, 30 seconds / 1, 5, 15, 30 minutes).

HS210 - for the HS210, could you send me a log of you doing following:

- Open log
- Set debug log on
- run save preferences
- on, wait 10 seconds
- off, wait 10 seconds
- 

There may be a problem with the socket connect assumption I make for the device - easily fixed.

**Comment by gmaus60** [comment]
Here is the log for HS210.  I hit 'on' at 1 second past and 'off' at 11 seconds past....

![image](https://user-images.githubusercontent.com/78964938/107809189-4c3f3280-6d30-11eb-8246-fe1443171251.png)

**Comment by DaveGut** [comment]
OK.  The code has the correct assumptions.  Thanks for the input.
