### ISSUE TITLE
Add KL125 as a valid Color bulb

### ISSUE THREAD

**Issue by CotOTK** [DaveGut/HubitatActive#8]
Recently purchased a KL125 Color bulb and when I went to add it, it did not show as a new device.  Thanks in advance.

**Comment by DaveGut** [comment]
You need to upgrade to the latest version of the Kasa Integration.  The App has been upgraded and is now model agnostic.  Latest version is 6.3.0.  PS:  I have successfully installed the KL125 on all versions above 6.0.

Dave

**Comment by CotOTK** [comment]
I am using version 6.3.0 already.

**Comment by DaveGut** [comment]
Item to check.  Then I need logs:
Can bulb be controlled via the Kasa phone app?
Is the Kasa Color Bulb Driver installed?
Is the bulb on the same network segment as the Hub.

If all of these are true, then I need to see the Application logs for an installation attempt.

Dave

**Comment by CotOTK** [comment]
They are all true.  Just to clarify what log you need and the method I am
installing.  I go to the app and click on Install Kasa Devices.  Once I do
it shows 0 devices to add.  I enabled debug logging and went to the logs
menu item and gathered the logs for the app.  Is that correct?

**Comment by DaveGut** [comment]
Yes, that is the log.

**Comment by CotOTK** [comment]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:49.644 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateChildDeviceData
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.417 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Abbys Fan added to array. Data = [dni:98DAC459CD0E,
type:Kasa Plug Switch, feature:TIM, alias:Abbys Fan, model:HS103,
deviceId:800673C6E09E2BC056EEDA28939CF2D71BB82FBF, ip:10.100.100.172]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.414 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Plug Switch Abbys Fan added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.410 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = 98DAC459CD0E
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.407 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
parseDeviceData: [sw_ver:1.1.3 Build 200804 Rel.095135, hw_ver:2.1,
model:HS103(US), deviceId:800673C6E09E2BC056EEDA28939CF2D71BB82FBF,
oemId:24B27E003E98D053CF8B51CE8086FDA8,
hwId:18967AEED1C89BED1BBC7F62FD06468A, rssi:-65, , alias:Abbys Fan,
status:new, mic_type:IOT.SMARTPLUGSWITCH, feature:TIM,
mac:98:DA:C4:59:CD:0E, updating:0, led_off:0, relay_state:1, on_time:72170,
active_mode:none, icon_hash:, dev_name:Smart Wi-Fi Plug Lite,
next_action:[type:-1], err_code:0] // 10.100.100.172
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.391 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Lamp added to array. Data = [dni:98DAC459C041, type:Kasa
Plug Switch, feature:TIM, alias:Lamp, model:HS103,
deviceId:8006E99E83D991EA5C6E9D91F24B68341BB82569, ip:10.100.100.171]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.388 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Plug Switch Lamp added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.385 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = 98DAC459C041
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.381 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
parseDeviceData: [sw_ver:1.1.3 Build 200804 Rel.095135, hw_ver:2.1,
model:HS103(US), deviceId:8006E99E83D991EA5C6E9D91F24B68341BB82569,
oemId:24B27E003E98D053CF8B51CE8086FDA8,
hwId:18967AEED1C89BED1BBC7F62FD06468A, rssi:-57, , alias:Lamp, status:new,
mic_type:IOT.SMARTPLUGSWITCH, feature:TIM, mac:98:DA:C4:59:C0:41,
updating:0, led_off:0, relay_state:0, on_time:0, active_mode:none,
icon_hash:, dev_name:Smart Wi-Fi Plug Lite, next_action:[type:-1],
err_code:0] // 10.100.100.171
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.377 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Steves Lamp added to array. Data = [dni:3C846AB4F24F,
type:Kasa Plug Switch, feature:TIM, alias:Steves Lamp, model:HS103,
deviceId:8006E031162BF08EF442519FEF1301AE1D5F905C, ip:10.100.100.170]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.371 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Plug Switch Steves Lamp added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.368 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = 3C846AB4F24F
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:44.364 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
parseDeviceData: [sw_ver:1.1.3 Build 200804 Rel.095135, hw_ver:2.1,
model:HS103(US), deviceId:8006E031162BF08EF442519FEF1301AE1D5F905C,
oemId:24B27E003E98D053CF8B51CE8086FDA8,
hwId:18967AEED1C89BED1BBC7F62FD06468A, rssi:-63,, l, alias:Steves Lamp,
status:new, mic_type:IOT.SMARTPLUGSWITCH, feature:TIM,
mac:3C:84:6A:B4:F2:4F, updating:0, led_off:0, relay_state:0, on_time:0,
active_mode:none, icon_hash:, dev_name:Smart Wi-Fi Plug Lite,
next_action:[type:-1], err_code:0] // 10.100.100.170
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.709 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Lamp - Jenny added to array. Data = [dni:D847327FC62E,
type:Kasa Plug Switch, feature:TIM, alias:Lamp - Jenny, model:HS103,
deviceId:8006F7B6808758C32852BD6EEF11E4711D1197AD, ip:10.100.100.146]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.706 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Plug Switch Lamp - Jenny added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.702 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = D847327FC62E
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.699 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
parseDeviceData: [sw_ver:1.1.3 Build 200804 Rel.095135, hw_ver:2.1,
model:HS103(US), deviceId:8006F7B6808758C32852BD6EEF11E4711D1197AD,
oemId:24B27E003E98D053CF8B51CE8086FDA8,
hwId:18967AEED1C89BED1BBC7F62FD06468A, rssi:-59, , alias:Lamp - Jenny,
status:new, mic_type:IOT.SMARTPLUGSWITCH, feature:TIM,
mac:D8:47:32:7F:C6:2E, updating:0, led_off:0, relay_state:0, on_time:0,
active_mode:none, icon_hash:, dev_name:Smart Wi-Fi Plug Lite,
next_action:[type:-1], err_code:0] // 10.100.100.146
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.512 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Color Christmas Tree added to array. Data =
[dni:D847327FDE38, type:Kasa Plug Switch, feature:TIM, alias:Color
Christmas Tree, model:HS103,
deviceId:80067D83BBDBAB16FDCA335C05A5827C1D11A4DC, ip:10.100.100.138]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.507 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Plug Switch Color Christmas Tree added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.497 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = D847327FDE38
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:43.490 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
parseDeviceData: [sw_ver:1.1.3 Build 200804 Rel.095135, hw_ver:2.1,
model:HS103(US), deviceId:80067D83BBDBAB16FDCA335C05A5827C1D11A4DC,
oemId:24B27E003E98D053CF8B51CE8086FDA8,
hwId:18967AEED1C89BED1BBC7F62FD06468A, rssi:-58, , alias:Color Christmas
Tree, status:new, mic_type:IOT.SMARTPLUGSWITCH, feature:TIM,
mac:D8:47:32:7F:DE:38, updating:0, led_off:0, relay_state:0, on_time:0,
active_mode:none, icon_hash:, dev_name:Smart Wi-Fi Plug Lite,
next_action:[type:-1], err_code:0] // 10.100.100.138
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.961 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Jennys Charger added to array. Data = [dni:6032B123BC5E02,
type:Kasa Multi Plug, feature:TIM, alias:Jennys Charger, model:KP303,
deviceId:80062C18D2C139CFA1BFFCDB0F7147DB1D725BEB, ip:10.100.100.117,
plugNo:02, plugId:80062C18D2C139CFA1BFFCDB0F7147DB1D725BEB02]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.956 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Multi Plug Jennys Charger added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.950 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = 6032B123BC5E02
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.945 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Jennys Lamp added to array. Data = [dni:6032B123BC5E01,
type:Kasa Multi Plug, feature:TIM, alias:Jennys Lamp, model:KP303,
deviceId:80062C18D2C139CFA1BFFCDB0F7147DB1D725BEB, ip:10.100.100.117,
plugNo:01, plugId:80062C18D2C139CFA1BFFCDB0F7147DB1D725BEB01]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.941 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Multi Plug Jennys Lamp added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.937 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = 6032B123BC5E01
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.932 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Jennys Fan added to array. Data = [dni:6032B123BC5E00,
type:Kasa Multi Plug, feature:TIM, alias:Jennys Fan, model:KP303,
deviceId:80062C18D2C139CFA1BFFCDB0F7147DB1D725BEB, ip:10.100.100.117,
plugNo:00, plugId:80062C18D2C139CFA1BFFCDB0F7147DB1D725BEB00]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.926 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Multi Plug Jennys Fan added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.921 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = 6032B123BC5E00
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.910 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
parseDeviceData: [sw_ver:1.0.10 Build 200828 Rel.162602, hw_ver:1.0,
model:KP303(US), deviceId:80062C18D2C139CFA1BFFCDB0F7147DB1D725BEB,
oemId:94E91A49D434FE323E91459A808F3460,
hwId:FDE836D4DB9F379373AFE9BF3F5DCD2A, rssi:-62, , alias:TP-LINK_Power
Strip_BC5E, status:new, mic_type:IOT.SMARTPLUGSWITCH, feature:TIM,
mac:60:32:B1:23:BC:5E, updating:0, led_off:0, children:[[id:00, state:0,
alias:Jennys Fan, on_time:0, next_action:[type:-1]], [id:01, state:1,
alias:Jennys Lamp, on_time:268737, next_action:[type:-1]], [id:02, state:1,
alias:Jennys Charger, on_time:268737, next_action:[type:-1]]], child_num:3,
ntc_state:0, err_code:0] // 10.100.100.117
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.619 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Bedroom Fan added to array. Data = [dni:CC32E5E61299,
type:Kasa Plug Switch, feature:TIM, alias:Bedroom Fan, model:HS105,
deviceId:80069592705F8F92E690EE3B34851BFC1C8FFDE1, ip:10.100.100.107]
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.616 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: Kasa Plug Switch Bedroom Fan added to devices array.
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.612 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
updateDevices: dni = CC32E5E61299
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:42.608 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
parseDeviceData: [sw_ver:1.0.21 Build 200804 Rel.082407, hw_ver:3.3,
model:HS105(US), deviceId:80069592705F8F92E690EE3B34851BFC1C8FFDE1,
oemId:16DD56EA45BADD08327504B19CFBA217,
hwId:E48B1F649DC598BDE89F2216EE4FACAA, rssi:-63, , alias:Bedroom Fan,
status:new, mic_type:IOT.SMARTPLUGSWITCH, feature:TIM,
mac:CC:32:E5:E6:12:99, updating:0, led_off:0, obd_src:tplink,
relay_state:0, on_time:0, active_mode:none, icon_hash:, dev_name:Smart
Wi-Fi Plug Mini, next_action:[type:-1], err_code:0] // 10.100.100.107
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:39.641 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
findDevices: Searching for LAN deivces on IP Segment = 10.100.100
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:39.638 pm debug
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]:
addDevicesPage
app:865 <http://10.100.100.21/logs#app865>2021-04-13 04:11:34.520 pm info
<http://10.100.100.21/installedapp/configure/865>[KasaInt/6.3.0]: starting
Kasa Integration, Version 6.3.0

**Comment by DaveGut** [comment]
My KL125 SW version is 1.05 and HW version is 1.20. It is captured on the installation process.  One last test - then we go to a cloud installation.

- Open logging
- Install and run the application at https://raw.githubusercontent.com/DaveGut/Hubitat-TP-Link-Integration-DEPRECATED/master/FindByIp.groovy.
- Enter the IP address for your KL125
- It will provide a log similar to the below.
- (note, this app will exit with an error, that is because it was a quickie to test for access.)

app:14862021-04-13 03:53:55.408 pm infoFind Device: 
			Device found at IP 192.168.50.186
			DNI = C0C9E397CC11
			Type: Kasa Color Bulb
			Model: KL125(US)
			Alias: Reading Light

**Comment by DaveGut** [comment]
One note:  The polling process during installation is not perfect.  If a device is missing, I typically try again immediately.  Sometimes the devices appear to go into a sleep mode and the need to be awaken before you can discover them.  This is particularly true for my KL125.

**Comment by CotOTK** [comment]
So, time to eat some crow.  Turns out that someone had turned the switch
off on the lamp from the time I set it up on the app and when I tried to
add it to Hubitat.  Sorry for completely wasting your time. 😕

**Comment by DaveGut** [comment]
It happens.  Have fun and nice chatting with you.  Dave
