### ISSUE TITLE
Add LB130 as Color Bulb

### ISSUE THREAD

**Issue by drfant** [DaveGut/HubitatActive#9]
I have had an LB130 color bulb as a lamp in my office.  The KASA app shows it just find and works thru that app, but does not get added in Hubitat.  I upgraded the drivers and application to version 6.3. When I attempt to add the lamp i can see it listed but it does not add.  I have rebooted several times but see nothing.  At one point I did see something, but now it seems to have disappeared.  In looking at the logs, I do not see that lamp listed, but on previous log it was there.  this was from the log:

dev:132021-06-12 09:45:23.633 am warn[Color Bulb / 6.3.2 / Desklamp]| sendCmd: attribute connection not set.
dev:132021-06-12 09:39:44.437 am warn[Color Bulb / 6.3.2 / Desklamp]| sendCmd: attribute connection not set.
dev:132021-06-12 09:37:03.333 am warn[Color Bulb / 6.3.2 / Desklamp]| sendCmd: attribute connection not set.
dev:132021-06-12 09:14:19.770 am errorjava.lang.IllegalArgumentException: null on line 668 (off)
dev:132021-06-12 09:14:18.739 am warn[Color Bulb/6.1.1] Desklamp rawSocketTimeout: Quick Poll and Refresh Disabled.
dev:132021-06-12 09:14:18.711 am warn[Color Bulb/6.1.1] Desklamp rawSocketTimeout: Retry on error limit exceeded. Error count = 77.  Run Application to update IP.
dev:132021-06-12 09:11:29.848 am errorjava.lang.IllegalArgumentException: null on line 668 (on)
dev:132021-06-12 09:11:28.777 am warn[Color Bulb/6.1.1] Desklamp rawSocketTimeout: Quick Poll and Refresh Disabled.
dev:132021-06-12 09:11:28.753 am warn[Color Bulb/6.1.1] Desklamp rawSocketTimeout: Retry on error limit exceeded. Error count = 76.  Run Application to update IP.

I am new to hubitat and adding code or checking on all the settings. so any guidance will be appreciated.  Thanks

**Comment by DaveGut** [comment]
In the app, open the help page and read through the instructions carefully.  ReInstall from scratch and at the end is a recommendation for the data I need to resolve a problem.  I can not resolve with what you have reported.

**Comment by drfant** [comment]
Dave, Thanks very much.   Adding the Hubitat Package Manager and installing the KASA Integration made everything work perfectly.  It was much easier than doing it manually as I had before.
